# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ===== NPM =====
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/cms"
    target-branch: "development"
    schedule:
      interval: "weekly"
    groups:
      non-major-deps:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/web"
    target-branch: "development"
    schedule:
      interval: "weekly"
    groups:
      non-major-deps:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  # ===== DOCKER =====
  - package-ecosystem: "docker"
    directory: "/cms"
    target-branch: "development"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/web"
    target-branch: "development"
    schedule:
      interval: "weekly"

  # ===== GITHUB ACTIONS =====
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
